- name: Get disk space
  hosts: all

  tasks:
    - name: Run df command
      ansible.builtin.command: df -h
      register: df_output

    - name: Print disk space
      ansible.builtin.debug:
        var: df_output.stdout_lines
